//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afonsoft.Petz.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class petz_Rating
    {
        public int rating_id { get; set; }
        public string rating_comments { get; set; }
        public Nullable<int> insert_user_id { get; set; }
        public Nullable<int> insert_client_id { get; set; }
        public Nullable<int> rating_user_id { get; set; }
        public Nullable<int> rating_pet_id { get; set; }
        public Nullable<int> rating_client_id { get; set; }
        public Nullable<int> rating_company_id { get; set; }
        public Nullable<int> rating_value { get; set; }
        public Nullable<System.DateTime> date_insert { get; set; }
    
        public virtual petz_Clients petz_Clients { get; set; }
        public virtual petz_Clients petz_Clients1 { get; set; }
        public virtual petz_Companies petz_Companies { get; set; }
        public virtual petz_Pets petz_Pets { get; set; }
        public virtual petz_Users petz_Users { get; set; }
        public virtual petz_Users petz_Users1 { get; set; }
    }
}
