//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afonsoft.Petz.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class petz_Company_Work
    {
        public int work_id { get; set; }
        public int company_id { get; set; }
        public int work_start_time_min { get; set; }
        public int work_end_time_min { get; set; }
        public string work_week { get; set; }
        public int work_week_id { get; set; }
    
        public virtual petz_Companies petz_Companies { get; set; }
    }
}
