//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afonsoft.Petz.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class petz_Users_Role_Groups
    {
        public int role_group_id { get; set; }
        public int user_id { get; set; }
        public int users_role_group_id { get; set; }
    
        public virtual petz_Role_Groups petz_Role_Groups { get; set; }
        public virtual petz_Users petz_Users { get; set; }
    }
}
