//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afonsoft.Petz.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class petz_Pet_Scheduling
    {
        public int scheduling_id { get; set; }
        public int pet_id { get; set; }
        public int client_id { get; set; }
        public int company_address_id { get; set; }
        public Nullable<int> employees_id { get; set; }
        public Nullable<int> service_id { get; set; }
        public string scheduling_comments { get; set; }
        public System.DateTime scheduling_date_start { get; set; }
        public System.DateTime scheduling_date_end { get; set; }
        public int status_id { get; set; }
        public Nullable<int> insert_client_id { get; set; }
        public Nullable<int> update_client_id { get; set; }
        public Nullable<int> insert_user_id { get; set; }
        public Nullable<int> update_user_id { get; set; }
        public System.DateTime date_insert { get; set; }
        public Nullable<System.DateTime> date_update { get; set; }
        public Nullable<System.DateTime> date_delete { get; set; }
    
        public virtual petz_Clients petz_Clients { get; set; }
        public virtual petz_Clients petz_Clients1 { get; set; }
        public virtual petz_Clients petz_Clients2 { get; set; }
        public virtual petz_Company_Address petz_Company_Address { get; set; }
        public virtual petz_Employees petz_Employees { get; set; }
        public virtual petz_Pets petz_Pets { get; set; }
        public virtual petz_Status petz_Status { get; set; }
        public virtual petz_Users petz_Users { get; set; }
        public virtual petz_Users petz_Users1 { get; set; }
    }
}
