language: csharp
mono:
  - latest
os:
  - linux
  - osx
solution: Afonsoft.Petz/Afonsoft.Petz.sln
install:
  - nuget restore Afonsoft.Petz/Afonsoft.Petz.sln
script:
  - xbuild /p:Configuration=Debug Afonsoft.Petz/Afonsoft.Petz.sln
  - xbuild /p:Configuration=Release Afonsoft.Petz/Afonsoft.Petz.sln
cache:
  directories:
    - bin
