//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afonsoft.Petz.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Petz_dbEntities : DbContext
    {
        public Petz_dbEntities()
            : base("name=Petz_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<petz_Address> petz_Address { get; set; }
        public virtual DbSet<petz_Breed> petz_Breed { get; set; }
        public virtual DbSet<petz_Client_Address> petz_Client_Address { get; set; }
        public virtual DbSet<petz_Client_Company> petz_Client_Company { get; set; }
        public virtual DbSet<petz_Client_Pet> petz_Client_Pet { get; set; }
        public virtual DbSet<petz_Client_Phone> petz_Client_Phone { get; set; }
        public virtual DbSet<petz_Clients> petz_Clients { get; set; }
        public virtual DbSet<petz_Companies> petz_Companies { get; set; }
        public virtual DbSet<petz_Company_Address> petz_Company_Address { get; set; }
        public virtual DbSet<petz_Company_Phone> petz_Company_Phone { get; set; }
        public virtual DbSet<petz_Company_Service> petz_Company_Service { get; set; }
        public virtual DbSet<petz_Company_Status_Color> petz_Company_Status_Color { get; set; }
        public virtual DbSet<petz_Company_webcam> petz_Company_webcam { get; set; }
        public virtual DbSet<petz_Countries> petz_Countries { get; set; }
        public virtual DbSet<petz_Employees> petz_Employees { get; set; }
        public virtual DbSet<petz_Pet_Historic> petz_Pet_Historic { get; set; }
        public virtual DbSet<petz_Pet_Scheduling> petz_Pet_Scheduling { get; set; }
        public virtual DbSet<petz_Pet_Vaccination> petz_Pet_Vaccination { get; set; }
        public virtual DbSet<petz_Pet_Vaccination_Scheduling> petz_Pet_Vaccination_Scheduling { get; set; }
        public virtual DbSet<petz_Pets> petz_Pets { get; set; }
        public virtual DbSet<petz_Rating> petz_Rating { get; set; }
        public virtual DbSet<petz_Role_Groups> petz_Role_Groups { get; set; }
        public virtual DbSet<petz_Role_Groups_Roles> petz_Role_Groups_Roles { get; set; }
        public virtual DbSet<petz_Roles> petz_Roles { get; set; }
        public virtual DbSet<petz_Service> petz_Service { get; set; }
        public virtual DbSet<petz_Size> petz_Size { get; set; }
        public virtual DbSet<petz_Species> petz_Species { get; set; }
        public virtual DbSet<petz_States> petz_States { get; set; }
        public virtual DbSet<petz_Status> petz_Status { get; set; }
        public virtual DbSet<petz_Sub_Species> petz_Sub_Species { get; set; }
        public virtual DbSet<petz_Users> petz_Users { get; set; }
        public virtual DbSet<petz_Users_Role_Groups> petz_Users_Role_Groups { get; set; }
    }
}
