//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afonsoft.Petz.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class petz_Company_Status_Color
    {
        public int color_id { get; set; }
        public int company_id { get; set; }
        public int status_id { get; set; }
        public string status_color { get; set; }
        public string status_background_color { get; set; }
        public string status_border_color { get; set; }
        public string status_text_color { get; set; }
        public int insert_user_id { get; set; }
        public Nullable<int> update_user_id { get; set; }
        public System.DateTime date_insert { get; set; }
        public Nullable<System.DateTime> date_delete { get; set; }
    
        public virtual petz_Companies petz_Companies { get; set; }
        public virtual petz_Status petz_Status { get; set; }
        public virtual petz_Users petz_Users { get; set; }
        public virtual petz_Users petz_Users1 { get; set; }
    }
}
