//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afonsoft.Petz.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class petz_Company_webcam
    {
        public int webcam_id { get; set; }
        public int company_id { get; set; }
        public string webcam_url { get; set; }
        public string webcam_name { get; set; }
    
        public virtual petz_Companies petz_Companies { get; set; }
    }
}
