//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Afonsoft.Petz.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class petz_Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public petz_Address()
        {
            this.petz_Client_Address = new HashSet<petz_Client_Address>();
            this.petz_Company_Address = new HashSet<petz_Company_Address>();
            this.petz_Company_Phone = new HashSet<petz_Company_Phone>();
        }
    
        public int address_id { get; set; }
        public int state_id { get; set; }
        public string address_name { get; set; }
        public string address_number { get; set; }
        public string address_complement { get; set; }
        public string address_zip { get; set; }
        public Nullable<decimal> address_latitude { get; set; }
        public Nullable<decimal> address_longitude { get; set; }
        public Nullable<int> insert_client_id { get; set; }
        public Nullable<int> update_client_id { get; set; }
        public Nullable<int> insert_user_id { get; set; }
        public Nullable<int> update_user_id { get; set; }
        public System.DateTime date_insert { get; set; }
        public Nullable<System.DateTime> date_update { get; set; }
        public Nullable<System.DateTime> date_delete { get; set; }
        public string address_nickname { get; set; }
    
        public virtual petz_Clients petz_Clients { get; set; }
        public virtual petz_Clients petz_Clients1 { get; set; }
        public virtual petz_Users petz_Users { get; set; }
        public virtual petz_Users petz_Users1 { get; set; }
        public virtual petz_States petz_States { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<petz_Client_Address> petz_Client_Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<petz_Company_Address> petz_Company_Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<petz_Company_Phone> petz_Company_Phone { get; set; }
    }
}
